export { removeSizes } from './processors/removeSizes'
export { cssPrefix } from './processors/cssPrefix'
export { forceCurrentColor } from './processors/forceCurrentColor'
export { removeTags } from './processors/removeTags'
export { defineProcessor } from './processors/defineProcessor'
